name: test-check
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: npm install
        run: 
          make install
      - name: run test
        run: 
          make test